[build]
  base    = "Task_Management_Frontend"
  command = "npm run build"
  publish = "build"

[functions]
  directory = "server/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
